# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b52412258a04aadbfda41383f6bdb2d658b2a16e9725b6013d74048de9616f0cca52a66077a256fd295fcd90cc7adec45c8cc0557144d0eaa8b45649062dcd0

test:
  secret_key_base: 10595ee3425c0909bcbed3089936c5b7e40664cdb69629d866c60ca71a5a1a8fe39125102c4cb33bdb49ac443c9f0b52484cbcf9ed2cfcd287805744fab1433d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
